### ISSUE TITLE
It does't work with Unity Android Platform, What's wrong?

### ISSUE THREAD

**Issue by Enanyy** [piti6/UnityGpuInstancedAnimation#4]
Unity Version: 2018.2.13f1
I switch to Android platform in Build Settings window, and it does't Play Animation, But it can work with iOS platform.

**Comment by wuxingogo** [comment]
"#pragma target 4.5" is not supported on android.
Change to #pragma target 3.0.

**Comment by Enanyy** [comment]
Thank You!!
